<a href="https://colab.research.google.com/github/asilbek1301/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# pip install pandas

In [4]:
import pandas as pd

In [8]:
print(pd.__version__)

2.2.3

In [46]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [47]:
# Boshidan boshlab default 5ta datani tableda ko'rsatadi

df.head() # default 5 rows

# df.head(3)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [48]:
# Oxiridan boshlab default 5ta datani tableda ko'rsatadi

df.tail() # default 5 rows

# df.tail(2)

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [49]:
df.shape

(7, 2)

In [50]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [51]:
df.dtypes

cars      object
counts     int64
dtype: object

In [52]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [53]:
df.describe() # numerical columns only

# mean --> o'rtachasi
# std  --> qancha bir-biridan farq qiladi
# 25%  --> raqamlarning 25 foizi 2.5ga teng yoki kichik

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [55]:
df.iloc[1:5] # df dagi index orqali iloc[0] dagi datani olib beradi

# df.iloc[1:5]
# df.iloc[2:]

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [63]:
df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [68]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [78]:
df[df["cars"] == "Tesla"]

    cars  counts
3  Tesla       8

In [82]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.714285714285714)

In [83]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [84]:
df.min()

cars      BMW
counts      1
dtype: object

In [85]:
df.max()

cars      Volvo
counts        9
dtype: object

In [87]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [88]:
df.count()

cars      7
counts    7
dtype: int64

In [90]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [97]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [105]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [106]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [111]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [119]:
# df = pd.read_csv("Titanic-Dataset.csv")

df = pd.read_excel("output.xlsx")

df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [118]:
df.to_excel("output.xlsx")

In [122]:
# Series => 1d arraylar bilan ishlatiladi
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [125]:
cars_series = data_with_missing["cars"]
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']